config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments
  end
  resources :tags
  root to: 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments
    has_many :taggings
    has_many :tags, through: :taggings
    has_attached_file :image
    validates_attachment_content_type :image, :content_type => ["image/jpg","image/jpeg","image/png"]
    
    def tag_list
        self.tags.collect do |tag|
            tag.name
        end.join(', ')
    end

    def tag_list=(tags_string)
        tag_names = tags_string.split(',').collect{|s| s.strip.downcase}.uniq
        new_or_found_tags = tag_names.collect {|name| Tag.find_or_create_by(name: name)}
        self.tags = new_or_found_tags
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings, dependent: :destroy
    has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    include ArticlesHelper
    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
        @comment = Comment.new
        @comment.article_id = @article.id
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.save

        flash.notice = "Article '#{@article.title}' created!"

        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy

        flash.notice = "Article '#{@article.title}' destroyed!"

        redirect_to articles_path
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        @article.update(article_params)

        flash.notice = "Article '#{@article.title}' updated!"

        redirect_to article_path(@article)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @comment = Comment.new(comment_params)
        @comment.article_id = params[:article_id]

        @comment.save
        redirect_to article_path(@comment.article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
    end

    private
    def comment_params
        params.require(:comment).permit(:author_name, :body)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def index
        @tags = Tag.all
    end

    def show
        @tag = Tag.find(params[:id])
    end

    def destroy
        @tag = Tag.find(params[:id])
        @tag.destroy

        flash.notice = "Tag '#{@tag.name}' destroyed!"

        redirect_to tags_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def article_params
        params.require(:article).permit(:title, :body, :tag_list, :image)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
    <h4>Comment by <%=comment.author_name%></h4>
    <p class="comment"><%=comment.body%></p>
    <p>Posted <%=distance_of_time_in_words(comment.article.created_at, comment.created_at)%> later</p>
    <%= link_to 'Delete comment', [comment.article, comment], method: :delete, data: {confirm: "Are you sure?"}, :class => "button delete"%>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f|%>
    <ul>
        <% @article.errors.full_messages.each do |error|%>
            <li><%=error%></li>
        <%end%>
    </ul>
    <p>
        <%= f.label :title%>
        <%= f.text_field :title%>
    </p>
    <p>
        <%= f.label :body%>
        <%= f.text_area(:body, size: '30x10')%>
    </p>
    <p>
        <%= f.label :tag_list%>
        <%= f.text_field :tag_list%>
    </p>
    <p>
        <% if @article.image.exists?%>
            <%= image_tag @article.image.url%>
        <% end%>
        <%= f.label :image, "Attach an image"%>
        <%= f.file_field :image%>
    </p>
    <p>
        <%=f.submit%>
    </p>
<%end%>

app/views/articles/edit.html.erb
<h2>Edit an article</h2>

<%= render partial: 'form'%>

app/views/articles/index.html.erb
<h2>All articles</h2>
<ul id="articles">
    <% @articles.each do |article|%>
        <li>
            <h3><%= link_to article.title, article_path(article)%></h3>
            <p><%= article.body[0,50] + '...' %></p>
            <p class="tags"> Tags:&nbsp 
            <% article.tags.each do |tag|%>
                <%=link_to tag.name, tag_path(tag)%>,&nbsp

            <%end%>
            </p>
            <hr>
        </li>    
    <% end %>
</ul>

<%# <%= link_to "Create a new article", new_article_path%>

app/views/articles/new.html.erb
<h2>Create a New Article</h2>
<%= render partial: 'form'%>

app/views/articles/show.html.erb
<article>
<h2><%= @article.title%></h2>
<p class="tags">Tags:&nbsp 
    <% @article.tags.each do |tag|%>
        <%=link_to tag.name, tag_path(tag)%>,&nbsp
    <%end%>
</p>
<p>
    <% if @article.image.exists?%>
        <%= image_tag @article.image.url%>
    <% end%>
</p>
<p><%= @article.body%></p>
<%= link_to "Back to articles list", articles_path%>
<%= link_to "Edit", edit_article_path(@article), :class => "button"%>
<%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, :class => "button delete"%>
</article>
<hr>
<%= render partial: 'comments/form'%>
<hr>
<h3>Comments (<%=@article.comments.size%>)</h3>
<%= render partial: 'articles/comment', collection: @article.comments%>

app/views/comments/_form.html.erb
<div>
<h3>Post a comment</h3>
<%= form_for [@article, @comment] do |f|%>
    <p>
        <%= f.label :author_name, "Your name"%>
        <%= f.text_field :author_name%>
    </p>
    <p>
        <%= f.label :body, "Content"%>
        <%= f.text_area :body%>
    </p>
    <p>
        <%= f.submit 'Submit!'%>
    </p>
<%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Lato&amp;subset=latin-ext"%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="flash"><%=flash.notice%></p>
    <header>
      <h1>Articles Blog</h1>
    </header>
    <nav>
      <ul>
        <li><%= link_to 'All articles', articles_path%></li>
        <li><%= link_to 'Search by tags', tags_path%></li>
        <li><%= link_to 'Create a new article', new_article_path%></li>
      </ul>
    </nav>
    <main>
    <%= yield %>
    </main>
    <footer>
      <p>Norbert Bujny 2019</p>
    </footer>
  </body>
</html>

app/views/tags/index.html.erb
<h2>All tags</h2>
<ul id="tags">
    <% @tags.each do |tag|%>
        <li>
            <%= link_to tag.name, tag_path(tag)%>
            <%= link_to 'Delete', tag_path(tag), method: :delete, data: {confirm: "Are you sure?"}, :class => "button delete" %>
        </li>    
    <% end %>
</ul>

app/views/tags/show.html.erb
<h2>Articles Tagged with <%=@tag.name%></h2>

<ul id="articles">
    <% @tag.articles.each do |article|%>
        <li>
            <h3><%= link_to article.title, article_path(article)%></h3>
            <p><%= article.body[0,50] + '...' %></p>
            <p class="tags"> Tags: 
            <% article.tags.each do |tag|%>
                <%=link_to tag.name, tag_path(tag)%>, 

            <%end%>
            </p>
            <hr>
        </li>    
    <% end %>
</ul>